namespace Rcon.Commands
{
    public enum CommandType
    {
        Raw,
        GetChat,
        AllowPlayerToJoinNoCheck,
        BanPlayer,
        Broadcast,
        DestroyAllEnemies,
        DisableSpectator,
        EnableSpectator,
        DisallowPlayerToJoinNoCheck,
        DoExit,
        ForcePlayerToJoinTribe,
        GiveExpToPlayer,
        KickPlayer,
        KillPlayer,
        ListPlayers,
        SaveWorld,
        ServerChat,
        ServerChatTo,
        ServerChatToPlayer,
        SetMessageOfTheDay,
        SetTimeOfDay,
        ShowMessageOfTheDay,
        UnbanPlayer
    }
}
